# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Cypress.io CI

on:
  push:
    branches: [main, beta, chore/*, fix/*, ftr/*]
  pull_request:
    branches: [main, beta]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*

      - name: Use deps cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            ./.yarn/cache
          key: deps-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Use Gatsby cache
        uses: actions/cache@v2
        id: gatsby-cache
        with:
          path: |
            ./example/.cache
            ./example/public
          key: gatsby-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install deps
        # if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Use Cypress.io
        uses: cypress-io/github-action@v2
        env:
          DEBUG: '@cypress/github-action'
        with:
          install: false
          working-directory: integration-tests
          command: yarn test:cypress:ci
