name: GitHub Pages

on:
  push:
    branches: [main]
  pull_request:

jobs:
  deploy:
    name: GitHub Pages

    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*

      - name: Use deps cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ./.yarn/cache
          key: deps-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Use Gatsby cache
        uses: actions/cache@v2
        id: gatsby-cache
        with:
          path: |
            ./example-basic/.cache
            ./example-basic/public
            ./example-micro-frontends/root-app/.cache
            ./example-micro-frontends/root-app/public
          key: gatsby-gh-pages-${{ runner.os }}

      - name: Install deps
        run: yarn install --immutable

      - name: Build example-basic
        run: yarn workspace example-basic gatsby build --prefix-paths

      - name: Deploy example-basic
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./example-basic/public

      - name: Build example-micro-frontends
        run: yarn workspace @micro-app/root-app gatsby build --prefix-paths

      - name: Deploy example-micro-frontends
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./example-micro-frontends/root-app/public
          destination_dir: ./example-micro-frontends
