name: Jest # NB: The name is used in workflow_run

on:
  push:
    branches: [main, beta, chore/*, fix/*, ftr/*]
  pull_request:
    branches: [main, beta]

jobs:
  build:
    name: Jest tests

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [12.x, 14.x, 16.x]

    runs-on: ${{ matrix.platform }}
    # if: github.event.pull_request.merged

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Use deps cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ./.yarn/cache
          key: deps-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install deps
        run: yarn install --immutable

      - name: Use tests
        run: yarn test
