# This workflow will do a NPM release when git commit message is "Release 1.2.3"
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: npm-publish

on:
  push:
    branches:
      - [main, beta]

jobs:
  npm-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Publish if version has been updated
        uses: pascalgn/npm-publish-action@v1
        with:
          tag_name: 'v%s'
          tag_message: 'v%s'
          create_tag: 'true'
          commit_pattern: "^Release (\\S+)"
          workspace: './gatsby-plugin-wrap-pages'
          publish_command: 'yarn'
          publish_args: '--non-interactive'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
