# This workflow will do a NPM release when git commit message is "Release 1.2.3"
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: npm-publish

on:
  push:
    branches: [main, beta]

jobs:
  npm-publish:
    name: npm-publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*

      - name: Publish if version has been updated
        uses: mikeal/merge-release@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          DEPLOY_DIR: gatsby-plugin-wrap-pages
          SRC_PACKAGE_DIR: gatsby-plugin-wrap-pages
