# This workflow will do a NPM release when git commit message is "Release 1.2.3"
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: NPM

on:
  push:
    branches: [main, beta]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Use deps cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            ./.yarn/cache
          key: deps-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Set git config
        run: |
          git config --global user.name 'Tobias Høegh'
          git config --global user.email 'tobias@tujo.no'

      - name: Publish to NPM
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn workspace gatsby-plugin-wrap-pages release
